(add-to-list 'load-path' "~/.emacs.d/nial-mode")

(define-derived-mode nial-mode fundamental-mode "Nial"
  "Major mode for editing Nial code."
  (setq font-lock-defaults '(nial-font-lock-keywords))
  (setq-local indent-line-function 'insert-tab)
  (setq-default tab-width 2)
  (setq mode-name "Nial"))

(setq nial-font-lock-keywords
      `(
	("#.*$" . font-lock-comment-face)
	("\\$\\([^\\$]*\\)\\$" . font-lock-comment-face)
        ("\\bdefine function\\b " . font-lock-keyword-face)
	("\\bdefine method\\b " . font-lock-keyword-face)
	("\\bdefine type\\b " . font-lock-keyword-face)
	("\\bdefine utility\\b " . font-lock-keyword-face)
        ("\\bcall\\b " . font-lock-keyword-face)
        ("\\bif\\b " . font-lock-keyword-face)
	("\\bthen\\b" . font-lock-keyword-face)
	("\\bstop\\b" . font-lock-keyword-face)
	("\\btry\\b" . font-lock-keyword-face)
	("\\bcatch\\b " . font-lock-keyword-face)
	("\\buse\\b " . font-lock-keyword-face)
	("\\bcount\\b " . font-lock-keyword-face)
	("\\bwhile\\b " . font-lock-keyword-face)
	("\\bbreak\\b" . font-lock-keyword-face)
	("\\bnext\\b" . font-lock-keyword-face)
	("\\bextend\\b " . font-lock-keyword-face)
	("\\bfrom\\b " . font-lock-keyword-face)
	("\\bself\\b" . font-lock-keyword-face)
	("\\bto\\b " . font-lock-keyword-face)
	("\\bload\\b " . font-lock-keyword-face)
	("\\binto\\b " . font-lock-keyword-face)
	("\\bfor every\\b " . font-lock-keyword-face)
	("\\bin\\b " . font-lock-keyword-face)
	("\\breturn\\b" . font-lock-keyword-face)
        ("\\belse if\\b " . font-lock-keyword-face)
        ("\\belse\\b" . font-lock-keyword-face)
        ("\\band\\b " . font-lock-keyword-face)
        ("\\bor\\b " . font-lock-keyword-face)
        ("\\bnot\\b " . font-lock-keyword-face)
	("\\bcreate\\b " . font-lock-keyword-face)
	("\\blet user assign\\b " . font-lock-builtin-face)
	("\\bdisplay\\b " . font-lock-builtin-face)
	("\\bcopy\\b " . font-lock-builtin-face)
	("\\parent\\b" . font-lock-builtin-face)
        ("\\bTrue\\|False\\|Null\\b" . font-lock-constant-face)
        ("\\bdefine function\\s-+\\([[:alnum:]_*[:alnum:]*]+\\)" 1 font-lock-function-name-face)
	("\\bdefine method\\s-+\\([[:alnum:]_*[:alnum:]*]+\\)" 1 font-lock-function-name-face)
	("\\bdefine type\\s-+\\([[:upper:]_*[:alnum:]*]+\\)" 1 'font-lock-type-face)
	("\\b[A-Z][A-Z][A-Z_0-9]*\\b" . font-lock-constant-face)
	("\\b[A-Z]\\w*\\b" . font-lock-type-face)
	("\\<[0-9]+\\(\\.[0-9]*\\)?\\>" . font-lock-constant-face)
	("\\b\\w+\\b" . font-lock-variable-name-face)
	))
